language: go

go:
  - 1.13.x

os:
  - linux

env:
  global:
  - GO111MODULE=on

install:
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -u golang.org/x/lint/golint
  - go mod download

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...

script:
  - ulimit -n 8192 # prevent errors from too many open files
  - diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
  # currently the codebase fails this heavily, so we wont do it now
  # - diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
  - make verifiers
  - go test -race -short -coverprofile=coverage.txt ./...
  - go test -race -short -tags=openssl -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build